name: UEFI Build
on:
  workflow_dispatch:
  
jobs:
  build:
     runs-on: ubuntu-20.04
     permissions:
      contents: write
     steps:
      - name: Clone Repo
        run: |
         git clone https://github.com/RadGoodNow/edeka2-msm8939v2 buildit/ && cd buildit
         chmod 755 build_ido.sh
         bash ci-build.sh
      
      
